# Below server port only useful in local development environment
# server:
#   port: 8081
---
spring:
  #config:
   #activate:
    #on-profile: local
  #spring.data.mongodb.host: mongodb
  profiles: local
  data:
    mongodb:
      uri: mongodb+srv://training_rw_user:training_rw_password@training-cluster-dev.z7ar8.mongodb.net/customer-db
datastore:
  mongodb:
    collection:
      name: customer-coll-local
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb+srv://training_rw_user:training_rw_password@training-cluster-dev.z7ar8.mongodb.net/customer-db
datastore:
  mongodb:
    collection:
      name: customer-coll-dev
